export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const THINGS_LOADING = 'THINGS_LOADING';
export const THINGS_FAILED = 'THINGS_FAILED';
export const ADD_THINGS = 'ADD_THINGS';

export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';